FROM ubuntu:22.04

# Install base utilities
RUN apt-get update \
    && apt-get install -y build-essential wget python3-distutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# Use architecture detection to download the correct Miniconda installer
RUN arch=$(uname -m) && \
    if [ "$arch" = "x86_64" ]; then \
        wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh; \
    elif [ "$arch" = "aarch64" ]; then \
        wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O ~/miniconda.sh; \
    else \
        echo "Unsupported architecture: $arch"; \
        exit 1; \
    fi && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda \
    && rm ~/miniconda.sh

# Create base environment with minimal dependencies
COPY src/services/base/environment.yml .
RUN conda env create --name service -f environment.yml