channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - pip
    - setuptools
    - git+https://github.com/ndif-team/nnsight@dev
    # Telemetry
    - prometheus_client
    - python-logging-loki
    # PyTorch with Apple Silicon MPS support (will fallback to CPU on other platforms)
    - torch>=2.0.0
    - torchvision
    - torchaudio
